import type { Scan, Report, IssueCard } from "./site-check-types";

const mockIssues: IssueCard[] = [
  {
    id: "1",
    module: "technical",
    severity: "critical",
    title: "Отсутствует meta description",
    found: "Тег <meta name=\"description\"> не найден на странице",
    location: "<head> — отсутствует тег",
    why_it_matters: "Яндекс и Google используют description для сниппета в выдаче. Без него CTR падает на 20–30%",
    how_to_fix: "Добавьте <meta name=\"description\" content=\"...\"> в <head> с описанием до 160 символов",
    example_fix: '<meta name="description" content="SEO-продвижение сайтов в Москве — аудит, оптимизация, рост трафика от 30% за 3 месяца">',
    visible_in_preview: true,
  },
  {
    id: "2",
    module: "content",
    severity: "critical",
    title: "Дублирующийся H1",
    found: "Найдено 3 тега <h1> на одной странице",
    location: "Главная страница — строки 45, 120, 230",
    why_it_matters: "Несколько H1 сбивают поисковые системы: непонятно, какой заголовок главный",
    how_to_fix: "Оставьте один <h1>, остальные замените на <h2> или <h3>",
    example_fix: "<h1>Продвижение сайтов</h1>\n<h2>Наши услуги</h2>\n<h2>Преимущества</h2>",
    visible_in_preview: true,
  },
  {
    id: "3",
    module: "technical",
    severity: "high",
    title: "robots.txt блокирует CSS/JS",
    found: "Disallow: /assets/ в robots.txt блокирует стили и скрипты",
    location: "/robots.txt — строка 5",
    why_it_matters: "Googlebot не может отрендерить страницу без CSS/JS, что ухудшает ранжирование",
    how_to_fix: "Уберите блокировку CSS и JS файлов из robots.txt",
    example_fix: "User-agent: *\nAllow: /assets/css/\nAllow: /assets/js/",
    visible_in_preview: true,
  },
  {
    id: "4",
    module: "direct",
    severity: "high",
    title: "Заголовки не подходят для автотаргетинга",
    found: "H1 и Title не содержат коммерческих ключевых слов",
    location: "<title> и <h1>",
    why_it_matters: "Яндекс.Директ автотаргетинг берёт ключи из заголовков — без них показы будут нерелевантными",
    how_to_fix: "Включите в Title и H1 основные коммерческие запросы",
    example_fix: "<title>SEO-продвижение сайтов в Москве — заказать аудит и оптимизацию</title>",
    visible_in_preview: true,
  },
  {
    id: "5",
    module: "schema",
    severity: "medium",
    title: "Нет Schema.org разметки",
    found: "На странице отсутствует JSON-LD или Microdata",
    location: "Вся страница — нет структурированных данных",
    why_it_matters: "Без Schema.org страница не получит расширенные сниппеты и теряет видимость в AI-поиске",
    how_to_fix: "Добавьте JSON-LD разметку Organization и/или WebPage",
    example_fix: '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Organization","name":"..."}</script>',
    visible_in_preview: true,
  },
  {
    id: "6",
    module: "ai",
    severity: "medium",
    title: "Контент не структурирован для LLM",
    found: "Нет FAQ-блока, нет нумерованных списков с инструкциями",
    location: "Основной контент",
    why_it_matters: "AI-системы предпочитают чётко структурированный контент с вопросами и ответами",
    how_to_fix: "Добавьте секцию FAQ с вопросами целевой аудитории",
    example_fix: "<h2>Часто задаваемые вопросы</h2>\n<h3>Сколько стоит SEO-продвижение?</h3>\n<p>Стоимость зависит от...</p>",
    visible_in_preview: false,
  },
  {
    id: "7",
    module: "technical",
    severity: "medium",
    title: "Нет sitemap.xml",
    found: "Файл /sitemap.xml возвращает 404",
    location: "/sitemap.xml",
    why_it_matters: "Без sitemap поисковые роботы могут не найти все страницы сайта",
    how_to_fix: "Сгенерируйте sitemap.xml и укажите его в robots.txt",
    example_fix: "Sitemap: https://yoursite.ru/sitemap.xml",
    visible_in_preview: false,
  },
  {
    id: "8",
    module: "content",
    severity: "low",
    title: "Изображения без alt-атрибутов",
    found: "12 из 18 изображений не имеют alt-текста",
    location: "Различные секции страницы",
    why_it_matters: "Alt-тексты помогают поисковикам понять содержимое изображений и улучшают доступность",
    how_to_fix: "Добавьте описательный alt к каждому <img>",
    example_fix: '<img src="team.jpg" alt="Команда SEO-специалистов OwnDev в офисе">',
    visible_in_preview: false,
  },
  {
    id: "9",
    module: "direct",
    severity: "low",
    title: "Нет UTM-разметки внутренних CTA",
    found: "Кнопки \"Заказать\" ведут без UTM-параметров",
    location: "CTA-кнопки на главной",
    why_it_matters: "Без UTM невозможно отследить конверсии из Директа по конкретным посадочным",
    how_to_fix: "Добавьте UTM-метки к внутренним ссылкам для отслеживания",
    example_fix: "href=\"/order?utm_source=direct&utm_medium=cpc&utm_campaign=seo\"",
    visible_in_preview: false,
  },
  {
    id: "10",
    module: "competitors",
    severity: "high",
    title: "Конкуренты используют расширенные сниппеты",
    found: "3 из 5 конкурентов в топ-10 имеют FAQ-сниппеты",
    location: "SERP по запросу \"seo продвижение\"",
    why_it_matters: "Расширенные сниппеты занимают больше места в выдаче и повышают CTR",
    how_to_fix: "Добавьте FAQPage Schema.org разметку",
    example_fix: '{"@type":"FAQPage","mainEntity":[{"@type":"Question","name":"...","acceptedAnswer":{"@type":"Answer","text":"..."}}]}',
    visible_in_preview: false,
  },
];

export function createMockScan(url: string, mode: "page" | "site"): Scan {
  return {
    scan_id: crypto.randomUUID(),
    url,
    mode,
    status: "done",
    created_at: new Date().toISOString(),
    scores: { total: 52, seo: 45, direct: 38, schema: 25, ai: 40 },
    issues: mockIssues,
    theme: "SEO-продвижение",
    competitors: [
      { url: "competitor1.ru", scores: { total: 78, seo: 82, direct: 70, schema: 65, ai: 72 } },
      { url: "competitor2.ru", scores: { total: 85, seo: 88, direct: 75, schema: 80, ai: 78 } },
    ],
    keywords: [
      { keyword: "seo продвижение", volume: 12000, cluster: "основные" },
      { keyword: "seo аудит сайта", volume: 5400, cluster: "аудит" },
      { keyword: "продвижение в яндексе", volume: 8200, cluster: "основные" },
    ],
    minus_words: ["бесплатно", "скачать", "курс", "обучение", "вакансия"],
    expires_at: new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString(),
  };
}

export function createMockReport(scanId: string): Report {
  return {
    report_id: crypto.randomUUID(),
    scan_id: scanId,
    email: "",
    payment_status: "pending",
    payment_id: "",
    download_token: "",
    created_at: new Date().toISOString(),
  };
}
