/**
 * robots.txt builder — V3.
 *
 * Emits:
 *   • global User-agent: * with Allow / Disallow rules
 *   • per-AI-bot User-agent blocks (allow or disallow based on policy)
 *   • Sitemap directive(s)
 *   • Host directive (Yandex)
 */

import type { PassportInputs } from './types.js';
import { aiBotsForPolicy, AI_BOTS } from './aiBotsRegistry.js';

export interface RobotsOptions {
  disallow_paths?: string[];     // e.g. ['/admin', '/api', '/cart', '/checkout']
  allow_paths?: string[];
  crawl_delay?: number;          // seconds, only for non-Google bots
}

export function buildRobotsTxt(
  inputs: PassportInputs,
  options: RobotsOptions = {},
): { content: string; allowed: string[]; blocked: string[] } {
  const lines: string[] = [];
  const { allowed, blocked } = aiBotsForPolicy(inputs.ai_training_policy);

  const defaultDisallow = options.disallow_paths ?? [
    '/admin',
    '/api/',
    '/cart',
    '/checkout',
    '/account',
    '/login',
    '/*?utm_',
    '/*?yclid=',
    '/*?gclid=',
  ];
  const defaultAllow = options.allow_paths ?? ['/'];

  // Header comment
  lines.push(`# robots.txt for ${inputs.domain}`);
  lines.push(`# Generated by owndev.ru Site Formula V3`);
  lines.push(`# AI training policy: ${inputs.ai_training_policy}`);
  lines.push('');

  // Global block
  lines.push('User-agent: *');
  for (const p of defaultAllow) lines.push(`Allow: ${p}`);
  for (const p of defaultDisallow) lines.push(`Disallow: ${p}`);
  if (options.crawl_delay) lines.push(`Crawl-delay: ${options.crawl_delay}`);
  lines.push('');

  // AI bots — explicit blocks
  for (const bot of AI_BOTS) {
    lines.push(`# ${bot.vendor} — ${bot.purpose}`);
    lines.push(`User-agent: ${bot.user_agent}`);
    if (blocked.includes(bot.user_agent)) {
      lines.push('Disallow: /');
    } else {
      lines.push('Allow: /');
      for (const p of defaultDisallow) lines.push(`Disallow: ${p}`);
    }
    lines.push('');
  }

  // Sitemap & Host
  lines.push(`Sitemap: ${inputs.base_url}/sitemap.xml`);
  lines.push(`Host: ${inputs.domain}`);

  return {
    content: lines.join('\n'),
    allowed,
    blocked,
  };
}
